<a href="https://colab.research.google.com/github/mubinui/ASSEMBLYCODES8086/blob/main/NLP01(a).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<b>Prerequisites for the NLP</b> 


1.   Information Extracction
2.   Rules and Heuristics 





Converting word to numbers <br>
<b>The techniques for converting words to numbers are</b> 

1.   Unique Numbers 
2.   One hot encoding 
3.   Word embeddings 
     1.  TF-IDF 
     2.  Word2Vec  






<b> The techniques to compute word embedding </b>


1.   Using supervised Learning 
2.   Used self-supervised learning 
    1. Word2vec
    2. Globe



Supervised Learning for word embedding.

In [22]:
import numpy as np 
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [23]:
reviews = [
           'nice food',
           'amazing resturant',
           'too good',
           'just loved it !',
           'will go again',
           'horrible food',
           'never go there',
           'poor service',
           'poor quality',
           'needs improvement'
]

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [3]:
#Converting reviews one hot vector 
one_hot('amazing resturant',5000)

[2162, 4012]

In [24]:
vocab_size = 50
encoded_reviews = [one_hot(i, vocab_size) for i in reviews]
print(encoded_reviews)

[[5, 18], [3, 12], [40, 38], [34, 26, 39], [42, 33, 19], [4, 18], [47, 33, 37], [1, 29], [1, 11], [10, 10]]


In [25]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[ 5 18  0]
 [ 3 12  0]
 [40 38  0]
 [34 26 39]
 [42 33 19]
 [ 4 18  0]
 [47 33 37]
 [ 1 29  0]
 [ 1 11  0]
 [10 10  0]]


Creating the model 

In [31]:
embedded_vector_size = 4
model = Sequential()
#the first layer will be embedding layer
model.add(Embedding(vocab_size,
                    embedded_vector_size,
                    input_length = max_length,
                    name = "embedding"
                    ))
# for the later use we need to flaten the layer first 
model.add(Flatten())

# For the next layer we need a neuron with a sigmoid activation function 
model.add(Dense(1, activation='sigmoid'))

In [32]:
X = padded_reviews
y = sentiment 

In [33]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              200       
                                                                 
 flatten_3 (Flatten)         (None, 12)                0         
                                                                 
 dense_3 (Dense)             (None, 1)                 13        
                                                                 
Total params: 213
Trainable params: 213
Non-trainable params: 0
_________________________________________________________________


In [34]:
model.fit(X, y, epochs=300, verbose=2)

Epoch 1/300
1/1 - 0s - loss: 0.6973 - accuracy: 0.4000 - 484ms/epoch - 484ms/step
Epoch 2/300
1/1 - 0s - loss: 0.6961 - accuracy: 0.5000 - 7ms/epoch - 7ms/step
Epoch 3/300
1/1 - 0s - loss: 0.6948 - accuracy: 0.5000 - 7ms/epoch - 7ms/step
Epoch 4/300
1/1 - 0s - loss: 0.6936 - accuracy: 0.5000 - 8ms/epoch - 8ms/step
Epoch 5/300
1/1 - 0s - loss: 0.6923 - accuracy: 0.6000 - 6ms/epoch - 6ms/step
Epoch 6/300
1/1 - 0s - loss: 0.6911 - accuracy: 0.6000 - 6ms/epoch - 6ms/step
Epoch 7/300
1/1 - 0s - loss: 0.6899 - accuracy: 0.6000 - 6ms/epoch - 6ms/step
Epoch 8/300
1/1 - 0s - loss: 0.6886 - accuracy: 0.6000 - 6ms/epoch - 6ms/step
Epoch 9/300
1/1 - 0s - loss: 0.6874 - accuracy: 0.7000 - 8ms/epoch - 8ms/step
Epoch 10/300
1/1 - 0s - loss: 0.6861 - accuracy: 0.8000 - 8ms/epoch - 8ms/step
Epoch 11/300
1/1 - 0s - loss: 0.6849 - accuracy: 0.8000 - 8ms/epoch - 8ms/step
Epoch 12/300
1/1 - 0s - loss: 0.6837 - accuracy: 0.8000 - 7ms/epoch - 7ms/step
Epoch 13/300
1/1 - 0s - loss: 0.6824 - accuracy: 0.8000 -

In [35]:
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 118ms/step - loss: 0.2077 - accuracy: 1.0000


1.0

In [36]:
weights = model.get_layer('embedding').get_weights()[0]

In [37]:
len(weights)

50

In [38]:
weights[3]

array([ 0.34924263,  0.32626715,  0.42113486, -0.29705042], dtype=float32)

In [39]:
weights[5]

array([ 0.37122703,  0.355226  ,  0.40714738, -0.30786824], dtype=float32)